CREATE TABLE TB_PLATO (
    ID_PLATO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(25) NOT NULL,
    PRECIO NUMERIC (10,2) NOT NULL,
    STOCK INT DEFAULT 1 NOT NULL,
    TIPO_PLATO CHAR(3) NOT NULL,
    IMAGEN VARCHAR(150) NULL,
	CALIFICACION INT DEFAULT 0,
    CONSTRAINT TP_PLATO_CHECK CHECK (TIPO_PLATO IN('ENT','SEG','POS','BEB'))
);

