CREATE TABLE TB_PLATO (
    ID_PLATO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL (10,2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    TIPO_PLATO CHAR(1) NOT NULL,
    IMAGEN VARCHAR(150) NULL,
    CONSTRAINT TP_PLATO_CHECK CHECK (TIPO_PLATO IN ('E','S','P','B'))
);

CREATE TABLE TB_ETIQUETA (
    ID_ETIQUETA SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100) NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_PLATO_ETIQUETAS (
    ID_PLATO_ETIQUETA SERIAL PRIMARY KEY,
    ID_PLATO INT NOT NULL,
    ID_ETIQUETA INT NOT NULL,
    FOREIGN KEY (ID_PLATO) REFERENCES TB_PLATO(ID_PLATO) ON DELETE CASCADE,
    FOREIGN KEY (ID_ETIQUETA) REFERENCES TB_ETIQUETA(ID_ETIQUETA) ON DELETE CASCADE,
    UNIQUE (ID_PLATO, ID_ETIQUETA)
);