CREATE TABLE TB_PLATO (
    ID_PLATO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL (10,2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    TIPO_PLATO CHAR(1) NOT NULL,
    IMAGEN VARCHAR(150) NULL,
    CONSTRAINT TP_PLATO_CHECK CHECK (TIPO_PLATO IN ('E','S','P','B'))
);
