CREATE TABLE TB_ETIQUETA (
    ID_ETIQUETA SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100) NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_PLATO_ETIQUETAS (
    ID_PLATO_ETIQUETA SERIAL PRIMARY KEY,
    ID_PLATO INT NOT NULL,
    ID_ETIQUETA INT NOT NULL,
    FOREIGN KEY (ID_ETIQUETA) REFERENCES TB_ETIQUETA(ID_ETIQUETA) ON DELETE CASCADE,
    UNIQUE (ID_PLATO, ID_ETIQUETA)
);