CREATE TABLE TB_TEMATICA (
    ID_TEMATICA SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(25) NOT NULL
);

CREATE TABLE TB_EVENTO(
    ID_EVENTO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(120) NOT NULL,
    ID_TEMATICA INT NOT NULL,
    FECHA DATE NOT NULL DEFAULT CURRENT_DATE,
    HORA TIME NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    AFORO INT DEFAULT 0,  -- CAPACIDAD MAXIMA DE UN EVENTO DIFERENT A CUPOS 
	CUPOS INT DEFAULT 0, -- SE AGREGA ESTO PARA VERIFICAR CUANTOS CUPOS QUDAN DE UN EVNTO
	CALIFICACION INT DEFAULT 0,
    IMAGEN VARCHAR(150) NULL,
    FOREIGN KEY (ID_TEMATICA) REFERENCES TB_TEMATICA(ID_TEMATICA)
);

CREATE TABLE TB_EVENTO_MESA(
    ID_EVENTO_MESA SERIAL PRIMARY KEY,
    ID_EVENTO INT NOT NULL,
    ID_MESA INT NOT NULL, -- Solo ID, no FK (está en otro microservicio)
    FECHA_DESDE DATE NOT NULL,
    FECHA_HASTA DATE NOT NULL,
    FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO(ID_EVENTO),
    CONSTRAINT UQ_EVENTO_MESA UNIQUE(ID_EVENTO, ID_MESA)
);