CREATE TABLE TB_TEMATICA (
    ID_TEMATICA SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE TB_EVENTO (
    ID_EVENTO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    ID_TEMATICA INT NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    COSTO_EVENTO DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    IMAGEN VARCHAR(150) NULL,
    ESTADO VARCHAR(15) NOT NULL CHECK (ESTADO IN ('ACTIVO','CANCELADO')),
    FOREIGN KEY (ID_TEMATICA) REFERENCES TB_TEMATICA(ID_TEMATICA)
);

CREATE TABLE TB_EVENTO_MESA (
    ID_EVENTO_MESA SERIAL PRIMARY KEY,
    ID_EVENTO INT NOT NULL,
    ID_MESA INT NOT NULL, -- Solo ID, no FK (esta en otro microservicio)
    FECHA_DESDE TIMESTAMP NOT NULL,
    FECHA_HASTA TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO (ID_EVENTO),
    CONSTRAINT UQ_EVENTO_MESA UNIQUE(ID_EVENTO, ID_MESA),
    CONSTRAINT CK_EVENTO_MESA_FECHAS CHECK (FECHA_HASTA > FECHA_DESDE)
);