CREATE TABLE TB_MESA(
    ID_MESA SERIAL PRIMARY KEY,
    NUMERO_MESA INT NOT NULL UNIQUE,
    CAPACIDAD INT NOT NULL,
    TIPO VARCHAR(3) NOT NULL,
    ESTADO VARCHAR(3) NOT NULL,
    CONSTRAINT TIPO_CHECK_IN CHECK (TIPO IN('SAL','EVE')),
    CONSTRAINT TIPO_ESTADO_IN CHECK (ESTADO IN('LIB','OCU','RES'))
);

