CREATE TABLE TB_PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY,
    ID_MESA INT NOT NULL, -- Solo ID (Table Service)
    ID_USUARIO INT NOT NULL, -- Solo ID mesero (User Service)
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SUBTOTAL NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    TOTAL NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    ESTADO VARCHAR(3) NOT NULL CHECK (ESTADO IN ('PEN','PRO','PAG','ANU'))
);

CREATE TABLE TB_DETALLE_PEDIDO (
    ID_DETALLE SERIAL PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PLATO INT NOT NULL, -- Solo ID (Menu Service)
    CANTIDAD INT NOT NULL,
	ESTADO VARCHAR(3) NOT NULL CHECK(ESTADO IN('PED','ENT')), --PEDIDO, ENTREGADO
    PRECIO_UNITARIO NUMERIC(10,2) NOT NULL,
    SUBTOTAL NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO(ID_PEDIDO)
);