CREATE TABLE TB_PAGO (
    ID_PAGO SERIAL PRIMARY KEY,
    ID_RESERVA INT NULL, -- Solo ID (Reservation Service)
    ID_PEDIDO INT NULL, -- Solo ID (Order Service)
    ID_USUARIO INT NOT NULL, -- Solo ID cajero (User Service)
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MONTO NUMERIC(10,2) NOT NULL,
    METODO_PAGO VARCHAR(3) NOT NULL CHECK (METODO_PAGO IN ('EFE','TAR','TRA','YAP','PLI')),
    ESTADO VARCHAR(3) NOT NULL CHECK (ESTADO IN ('PAG','ANU'))
);