CREATE TABLE TB_PAGO (
    ID_PAGO SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_RESERVA INT NULL,  
    ID_PEDIDO INT NULL,   
    TIPO_PAGO VARCHAR(20) NOT NULL CHECK (TIPO_PAGO IN ('DR', 'PP')), -- DEPOSITO RESERVA / PAGO PEDIDO
    MONTO DECIMAL(10,2) NOT NULL, -- PA deposito es 15
    METODO_PAGO VARCHAR(20) NOT NULL, -- Yape, Plin, Tarjeta, Efectivo
    FECHA_PAGO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBSERVACIONES VARCHAR(150) NULL,
    CHECK (
        (ID_RESERVA IS NOT NULL AND ID_PEDIDO IS NULL AND TIPO_PAGO = 'DR') OR
        (ID_PEDIDO IS NOT NULL AND ID_RESERVA IS NULL AND TIPO_PAGO = 'PP')
    )
);