CREATE TABLE TB_NOTIFICACION (
    ID_NOTIFICACION SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    TIPO VARCHAR(20) NOT NULL 
        CHECK (TIPO IN ('RESERVA_CREADA', 'PEDIDO_PAGADO', 'EVENTO_CREADO')),
    TITULO VARCHAR(100) NOT NULL,
    MENSAJE VARCHAR(255) NOT NULL,
    LEIDA BOOLEAN DEFAULT FALSE,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    ID_RESERVA INT NULL,
    ID_PEDIDO INT NULL,
    ID_EVENTO INT NULL,
    
    CONSTRAINT check_tipo_referencia CHECK (
        (TIPO = 'RESERVA_CREADA' AND ID_RESERVA IS NOT NULL AND ID_PEDIDO IS NULL AND ID_EVENTO IS NULL) OR
        (TIPO = 'PEDIDO_PAGADO' AND ID_PEDIDO IS NOT NULL AND ID_RESERVA IS NULL AND ID_EVENTO IS NULL) OR
        (TIPO = 'EVENTO_CREADO' AND ID_EVENTO IS NOT NULL AND ID_RESERVA IS NULL AND ID_PEDIDO IS NULL)
    )
);

CREATE INDEX idx_notificaciones_usuario ON TB_NOTIFICACION(ID_USUARIO);
CREATE INDEX idx_notificaciones_leida ON TB_NOTIFICACION(LEIDA);
CREATE INDEX idx_notificaciones_tipo ON TB_NOTIFICACION(TIPO);
CREATE INDEX idx_notificaciones_fecha ON TB_NOTIFICACION(FECHA_CREACION DESC);
CREATE INDEX idx_notificaciones_usuario_leida ON TB_NOTIFICACION(ID_USUARIO, LEIDA);