CREATE TABLE TB_RESERVA (
    ID_RESERVA SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL, -- Solo ID (User Service)
    ID_MESA INT NOT NULL, -- Solo ID (Table Service)
    FECHA_HORA TIMESTAMP NOT NULL,
    ESTADO VARCHAR(3) NOT NULL CHECK (ESTADO IN ('PEN','PAG','ASI','CAN')),
    MONTO NUMERIC(10,2) NOT NULL DEFAULT 25.00,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);