CREATE TABLE TB_CALIFICACION (
    ID_CALIFICACION SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    TIPO_CALIFICACION VARCHAR(10) NOT NULL CHECK (TIPO_CALIFICACION IN ('P','E')),
    ID_ENTIDAD INT NOT NULL, -- ID del plato o evento
    PUNTUACION INT NOT NULL CHECK (PUNTUACION BETWEEN 1 AND 5),
    COMENTARIO VARCHAR(500) NULL,
    FECHA_CALIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ID_USUARIO, TIPO_CALIFICACION, ID_REFERENCIA)
);