CREATE TABLE TB_RESENA (
    ID_RESENA SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL, -- Quien escribe la reseña
    TIPO_ENTIDAD VARCHAR(20) NOT NULL, -- 'PLATO', 'EVENTO'
    ID_ENTIDAD INT NOT NULL, -- ID del plato, evento, etc.
    CALIFICACION INT NOT NULL CHECK (CALIFICACION BETWEEN 1 AND 5),
    COMENTARIO TEXT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(3) DEFAULT 'ACT' CHECK (ESTADO IN ('ACT','INA','REP')), -- Activa/Inactiva/Reportada
    
    CONSTRAINT CHK_TIPO_ENTIDAD CHECK (TIPO_ENTIDAD IN ('PLATO','EVENTO'))
);